version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: finwise-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: finwise
      MYSQL_USER: finwise_user
      MYSQL_PASSWORD: finwise_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - finwise-network

  # Backend Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: finwise-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=finwise
      - DB_USER=finwise_user
      - DB_PASSWORD=finwise_password
    depends_on:
      - mysql
    networks:
      - finwise-network
    volumes:
      - ./Backend:/app
      - /app/node_modules

  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: finwise-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - finwise-network
    volumes:
      - ./Frontend:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  finwise-network:
    driver: bridge
